include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - directives_ordering
    - lines_longer_than_80_chars
    - prefer_const_constructors
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - use_key_in_widget_constructors
    